PUT  http://localhost:4000/product/updateProduct
Content-Type: application/json

{ 
    "id":"6",
   "name":"moto", 
   "brand":"Nitro",
   "price":"34.000", 
   "type":"vehiculo", 
   "available":"disponible"
}